# Generated by Django 6.0.1 on 2026-01-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='Post excerpt', max_length=300),
        ),
    ]
