# Generated by Django 6.0.1 on 2026-01-27 09:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('technology', 'Technology'), ('design', 'Design')], default='TECHNOLOGY', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
